#!/usr/bin/env python3
"""
Test script for JWT authentication functionality
Tests token validation with tokens generated by format-a.vercel.app
"""

import os
import sys
import json
import jwt
from datetime import datetime, timedelta

# Add current directory to path
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

# Load environment variables from .env.local if it exists
def load_env():
    env_files = ['.env.local', '.env']
    for env_file in env_files:
        env_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), env_file)
        if os.path.exists(env_path):
            print(f"Loading environment from: {env_path}")
            with open(env_path, 'r') as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith('#') and '=' in line:
                        key, value = line.split('=', 1)
                        os.environ[key] = value
            return True
    return False

def test_jwt_utilities():
    """Test JWT authentication utilities"""
    print("=" * 60)
    print("TESTING JWT AUTHENTICATION UTILITIES")
    print("=" * 60)
    
    # Load environment
    env_loaded = load_env()
    print(f"Environment loaded: {env_loaded}")
    
    try:
        from auth_utils import validate_jwt_token, get_jwt_secret, test_jwt_validation
        print("✅ Successfully imported auth_utils")
    except ImportError as e:
        print(f"❌ Failed to import auth_utils: {e}")
        return False
    
    # Test JWT secret configuration
    print("\n1. Testing JWT Secret Configuration:")
    jwt_secret = get_jwt_secret()
    is_fallback = jwt_secret == 'fallback-secret-change-in-production'
    print(f"   JWT Secret configured: {'❌ Using fallback' if is_fallback else '✅ Environment variable set'}")
    print(f"   JWT Secret length: {len(jwt_secret)} characters")
    
    # Test token creation (simulating Node.js auth system)
    print("\n2. Testing Token Creation (simulating Node.js):")
    try:
        test_payload = {
            'userId': 'test-user-123',
            'email': 'test@example.com',
            'name': 'Test User',
            'picture': 'https://example.com/avatar.jpg',
            'googleId': 'google-123456789',
            'iat': int(datetime.utcnow().timestamp()),
            'exp': int((datetime.utcnow() + timedelta(days=7)).timestamp())
        }
        
        test_token = jwt.encode(test_payload, jwt_secret, algorithm='HS256')
        print(f"   ✅ Test token created successfully")
        print(f"   Token length: {len(test_token)} characters")
        print(f"   Token preview: {test_token[:50]}...")
        
    except Exception as e:
        print(f"   ❌ Failed to create test token: {e}")
        return False
    
    # Test token validation
    print("\n3. Testing Token Validation:")
    try:
        decoded = validate_jwt_token(test_token)
        if decoded:
            print("   ✅ Token validation successful")
            print(f"   Decoded user ID: {decoded.get('userId')}")
            print(f"   Decoded email: {decoded.get('email')}")
            print(f"   Decoded name: {decoded.get('name')}")
            print(f"   Token expires: {datetime.fromtimestamp(decoded.get('exp', 0))}")
        else:
            print("   ❌ Token validation failed")
            return False
    except Exception as e:
        print(f"   ❌ Token validation error: {e}")
        return False
    
    # Test invalid token
    print("\n4. Testing Invalid Token Handling:")
    invalid_tokens = [
        "invalid.token.here",
        "Bearer invalid.token.here",
        "",
        None
    ]
    
    for i, invalid_token in enumerate(invalid_tokens):
        result = validate_jwt_token(invalid_token) if invalid_token else None
        expected_result = result is None
        status = "✅" if expected_result else "❌"
        print(f"   {status} Invalid token {i+1}: {'None' if invalid_token is None else invalid_token[:20]}... -> {result is None}")
    
    # Test expired token
    print("\n5. Testing Expired Token:")
    try:
        expired_payload = {
            'userId': 'test-user-123',
            'email': 'test@example.com',
            'name': 'Test User',
            'iat': int((datetime.utcnow() - timedelta(days=8)).timestamp()),
            'exp': int((datetime.utcnow() - timedelta(days=1)).timestamp())  # Expired yesterday
        }
        
        expired_token = jwt.encode(expired_payload, jwt_secret, algorithm='HS256')
        result = validate_jwt_token(expired_token)
        
        if result is None:
            print("   ✅ Expired token correctly rejected")
        else:
            print("   ❌ Expired token incorrectly accepted")
            return False
            
    except Exception as e:
        print(f"   ❌ Expired token test error: {e}")
        return False
    
    print("\n6. Testing Environment Variables:")
    required_vars = ['JWT_SECRET', 'DATABASE_URL']
    for var in required_vars:
        value = os.environ.get(var)
        if value:
            print(f"   ✅ {var}: Set ({len(value)} characters)")
        else:
            print(f"   ❌ {var}: Not set")
    
    print("\n" + "=" * 60)
    print("JWT AUTHENTICATION TESTS COMPLETED")
    print("=" * 60)
    
    return True

def test_cors_headers():
    """Test CORS header functionality"""
    print("\n" + "=" * 60)
    print("TESTING CORS FUNCTIONALITY")
    print("=" * 60)
    
    try:
        from auth_utils import send_cors_headers
        print("✅ CORS utilities imported successfully")
        
        # Mock handler for testing
        class MockHandler:
            def __init__(self):
                self.headers_sent = {}
            
            def send_header(self, key, value):
                self.headers_sent[key] = value
        
        mock_handler = MockHandler()
        send_cors_headers(mock_handler)
        
        expected_headers = {
            'Access-Control-Allow-Origin': 'https://format-a.vercel.app',
            'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS',
            'Access-Control-Allow-Headers': 'Content-Type, Authorization',
            'Access-Control-Allow-Credentials': 'true'
        }
        
        print("\nCORS Headers Test:")
        all_correct = True
        for key, expected_value in expected_headers.items():
            actual_value = mock_handler.headers_sent.get(key)
            if actual_value == expected_value:
                print(f"   ✅ {key}: {actual_value}")
            else:
                print(f"   ❌ {key}: Expected '{expected_value}', got '{actual_value}'")
                all_correct = False
        
        return all_correct
        
    except Exception as e:
        print(f"❌ CORS test failed: {e}")
        return False

def main():
    """Run all authentication tests"""
    print("Starting JWT Authentication Tests...")
    print(f"Python version: {sys.version}")
    print(f"Working directory: {os.getcwd()}")
    
    # Run tests
    jwt_test_passed = test_jwt_utilities()
    cors_test_passed = test_cors_headers()
    
    print("\n" + "=" * 60)
    print("FINAL TEST RESULTS")
    print("=" * 60)
    print(f"JWT Authentication Tests: {'✅ PASSED' if jwt_test_passed else '❌ FAILED'}")
    print(f"CORS Functionality Tests: {'✅ PASSED' if cors_test_passed else '❌ FAILED'}")
    
    overall_success = jwt_test_passed and cors_test_passed
    print(f"\nOverall Result: {'✅ ALL TESTS PASSED' if overall_success else '❌ SOME TESTS FAILED'}")
    
    if not overall_success:
        print("\nPlease check the error messages above and ensure:")
        print("1. JWT_SECRET environment variable is set")
        print("2. PyJWT is installed (pip install PyJWT)")
        print("3. auth_utils.py is in the correct location")
    
    return overall_success

if __name__ == "__main__":
    success = main()
    sys.exit(0 if success else 1)