"""
Test endpoint for JWT authentication
Tests token validation with tokens generated by format-a.vercel.app
"""

from http.server import BaseHTTPRequestHandler
import json
import sys
import os

# Add parent directory to path to import auth_utils
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from auth_utils import AuthenticatedHandler, require_auth, validate_jwt_token, extract_token_from_request


class handler(BaseHTTPRequestHandler, AuthenticatedHandler):
    
    def do_GET(self):
        """Test endpoint that requires authentication"""
        # Extract token manually for testing
        token = extract_token_from_request(self)
        
        if not token:
            return self.send_error_response(401, "Authentication required", "No token provided")
        
        # Validate token
        user_data = validate_jwt_token(token)
        
        if not user_data:
            return self.send_error_response(401, "Invalid authentication", "Token validation failed")
        
        # Return user info if authentication successful
        response_data = {
            'authenticated': True,
            'user': {
                'userId': user_data.get('userId'),
                'email': user_data.get('email'),
                'name': user_data.get('name'),
                'googleId': user_data.get('googleId')
            },
            'token_info': {
                'exp': user_data.get('exp'),
                'iat': user_data.get('iat')
            },
            'message': 'Authentication successful'
        }
        
        return self.send_success_response(response_data)
    
    @require_auth
    def do_POST(self):
        """Test endpoint using the @require_auth decorator"""
        # Access authenticated user data
        user_data = {
            'userId': self.current_user['userId'],
            'email': self.current_user['email'],
            'name': self.current_user['name']
        }
        
        try:
            # Read request body
            content_length = int(self.headers.get('Content-Length', 0))
            if content_length > 0:
                post_data = self.rfile.read(content_length)
                request_data = json.loads(post_data.decode('utf-8'))
            else:
                request_data = {}
        except Exception as e:
            return self.send_error_response(400, "Invalid request data", str(e))
        
        response_data = {
            'authenticated': True,
            'user': user_data,
            'request_data': request_data,
            'message': 'POST request authenticated successfully'
        }
        
        return self.send_success_response(response_data)